name: Deploy Bicep File
on: [push]

jobs:
deploy-to-Azure:
runs-on: ubuntu-latest

steps:

- name: Checkout IaC
uses: actions/checkout@main
- name: Log into Azure
uses: azure/login@v1
with:
	creds: $ {{ secrets.AZURE_CREDENTIALS }}
	
- name: Deploy Bicep File
uses: azure/arm-deploy@v1
with:
	subscriptionId: 
	resourceGroupName: 
	template: ./azure-architecture.bicep
	parameters: ./azure-architecture-test.bicepparam
	failonStdErr: false